# Generated by Django 2.2.5 on 2019-09-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cag_name', models.CharField(max_length=100)),
                ('cag_img', models.ImageField(upload_to='cag')),
            ],
            options={
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_img', models.ImageField(upload_to='goods')),
                ('goods_num', models.IntegerField()),
                ('goods_price', models.FloatField(default=0)),
                ('goods_unit', models.CharField(default='500g', max_length=20)),
                ('goods_manufacturer', models.CharField(max_length=50)),
                ('goods_repertory', models.IntegerField()),
                ('cag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory')),
            ],
            options={
                'db_table': 'goodsinfo',
            },
        ),
    ]
