# Generated by Django 2.2.5 on 2019-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField(max_length=32)),
                ('phone', models.CharField(default='', max_length=11)),
                ('direction', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
